### ISSUE TITLE
Note on/off cycle cuts the notes in scale mode

### ISSUE THREAD

**Issue by desiremusic** [MiguelGuthridge/Novation-LaunchKey-Mk2-Script#37]
When in scale mode when you play the keys fast, the keys that play the same notes cancel each other therefore sound cuts off. 
You have to know which key plays which note so you don't play the same notes right after, so it kind of negates the point of having a scale mode, or am I using wrong? 

Instead a "white keys only" mode would work better. For example, put every note in C minor scale to white keys and disable black keys. So when you play only the white keys you play C minor scale.

**Comment by MaddyGuthridge** [comment]
This is an issue with the way FL Studio processes overlapping notes, which I doubt they will fix. I can add a workaround for it by using my note wrapper module, which I use for chord mode. I'll investigate this.

**Comment by MaddyGuthridge** [comment]
Fixed in v2.0.1
Enjoy!!!
