### ISSUE TITLE
Loop (shift) button makes the song stutter while the song plays

### ISSUE THREAD

**Issue by desiremusic** [MiguelGuthridge/Novation-LaunchKey-Mk2-Script#40]
When the song I'm working on plays, I want to select the channel rack or mixer for example, and to do that I have to push the shift button to get that window in front. But when you hold this button, it quickly switches between pattern/song mode (I guess) and therefore stutters/interrupts the playback of the song. You have to stop the song then use the shift menu instead.

Using the latest release.

**Comment by MaddyGuthridge** [comment]
This appears to be an issue with the playlist and piano roll processors. It doesn't happen in the channel rack, the mixer or the browser. I'll investigate further.

**Comment by MaddyGuthridge** [comment]
Ok so it appears to be an issue with the shift menu using the pitch-bend wheel as a jog wheel.

**Comment by desiremusic** [comment]
My pitch wheel and mod wheel are broken and they move by themselves. Maybe that's the problem.
Can you make an option to disable mod and pitch wheel?

**Comment by MaddyGuthridge** [comment]
Nah this is an issue with the script, I can reproduce it on my controller too. I think I've fixed it now. Can you check from this branch: https://github.com/MiguelGuthridge/Novation-LaunchKey-Mk2-Script/tree/fix-2.0.3

**Comment by desiremusic** [comment]
Yeah it fixed that problem but created another one. When in omni mode, pads won't trigger channels but does undo/redo and save project. Seems like shift key is stuck even after selecting omni mode. Same thing happened once when in scale mode but restart somehow solved it.

**Comment by MaddyGuthridge** [comment]
Can you try that branch again? I think I might have fixed it.

**Comment by desiremusic** [comment]
Yeah it works now with no problems at all. Thank you.

**Comment by MaddyGuthridge** [comment]
Great! I'll push this as an update now
