### ISSUE TITLE
Disabling Velocity Sensitivity in Omni Mode

### ISSUE THREAD

**Issue by desiremusic** [MiguelGuthridge/Novation-LaunchKey-Mk2-Script#41]
It would be great to have something like this.
Launchkey's pads are not really that sensitive anyways.
While playing trap drums, kick and snare almost always in full velocity. (or 80 instead of 100)

Please make a switch turn on and off velocity sensitivity in omni mode. 80% would be better instead of 100.

Thank you.

**Comment by MaddyGuthridge** [comment]
Will add in v2.1. Get keen!

**Comment by MaddyGuthridge** [comment]
I'll also be adding an option to set a custom velocity curve for the drum pads as a separate module.

**Comment by MaddyGuthridge** [comment]
Added in V2.1
